### ISSUE TITLE
function signature clarification

### ISSUE THREAD

**Issue by Kennyl** [pixmicat/pixmicat_modules#54]
bbcode

```
public function autoHookRegistBeforeCommit(&$name, &$email, &$sub, &$com, &$category, &$age, $dest, $resto, $imgWH){
```

others 

```
public function autoHookRegistBeforeCommit(&$name, &$email, &$sub, &$com, &$category, &$age, $dest, $isReply, $imgWH, &$status){
```

少數 7份之2

```
public function autoHookRegistBegin(&$name, &$email, &$sub, &$com, $upfileInfo, $accessInfo, $isReply){
```

多數 7份之5

```
function autoHookRegistBegin(&$name, &$email, &$sub, &$com, $upfileInfo, $accessInfo){
```

是否可以ommit 一些IN parm

**Comment by scribetw** [comment]
較後面的版本參數有變多，但PHP其實是可以相容的

http://pixmicat.wikidot.com/pmcapi:pms

**Comment by Kennyl** [comment]
autoHookRegistBegin

因為以前有用戶𣾀報, warning missing argument 7 in mod pushpost, 但我試不倒這warning.
而且要不要考慮有default parameter.
或者是 function (6 arg)  -chain-> function (7 arg)才會有這warning.

**Comment by scribetw** [comment]
應該是少參數的要把參數補齊，理論上參數只會多不會少。

這題要看Pixmicat!版本跟套件版本。
PMC 提供7個參數，套件只接6個，不會有問題。
PMC 提供6個參數，套件卻需要7個，就會有問題。
可能是PMC版本較舊，但是又抓較新的套件。反過來新PMC使用舊套件可能就沒問題。
