### ISSUE TITLE
Mod_Neta 失效？

### ISSUE THREAD

**Issue by LenKiMo** [pixmicat/pixmicat_modules#61]
在 8th.Release.4 發現啟用 Mod_Neta 后點擊“此處”按鈕始終顯示不出對應的內容。是 Mod 太久了不相適應了嗎？

**Comment by scribetw** [comment]
我看了 mod_neta，有用到 jQuery。
如果頁面沒有加上引用會沒有反應。

http://pixmicat.wikidot.com/pmcuse:setup#toc7
修改模板以加入引用再看看。

**Comment by LenKiMo** [comment]
加了相關的引用后成功了。
是我沒有仔細閱讀指南的錯誤，感謝相助。
